export const QUALITY_GATE_MODE = "hum-state-v2";

export const AUDIO_PIPELINE_THRESHOLDS = {
  rmsWindowMs: 80,
  noiseFloorMs: 500,
  activeNoiseMultiplier: 3.2,
  quietNoiseMultiplier: 1.7,
  activeMedianCapRatio: 0.6,
  quietMedianCapRatio: 0.45,
  absoluteActiveRms: 0.008,
  absoluteQuietRms: 0.0045,
  basicallySilentRms: 0.0035,
  basicallySilentPeak: 0.012,
  firstUseMinimumRms: 0.008,
  firstUseSoftRms: 0.014,
  minimumUsableSeconds: 3,
  targetHumSeconds: 12,
  minimumActiveFrameRatio: 0.22,
  borderlineActiveFrameRatio: 0.34,
  maximumQuietFrameRatio: 0.78,
  maximumClippedFrameRatio: 0.08,
  maximumNoiseFloorRms: 0.035,
  baselineSampleCount: 5,
  baselineMinimumCount: 3,
  faintBaselineRatio: 0.45,
  softBaselineRatio: 0.7,
  strongBaselineRatio: 1.5,
  qualityGate: {
    minimumDurationSec: 8,
    minimumActiveFrameRatio: 0.22,
    minimumPitchCoverage: 0.35,
    maximumSilenceRatio: 0.72,
    nearSilenceMeanRms: 0.006,
    softRms: 0.014,
    strongRms: 0.05,
    softBaselineRatio: 0.7,
    strongBaselineRatio: 1.5,
  },
} as const;
