import type { MusicTrack } from "@/types/hum";

export const demoMusicCatalog: MusicTrack[] = [
  {
    id: "demo-downshift-01",
    title: "Demo: Window Light",
    artist: "Hum Demo Catalogue",
    provider: "local",
    genreTags: ["ambient", "modern-classical"],
    bpm: 68,
    energy: 0.24,
    valence: 0.56,
    instrumentalness: 0.98,
    lyricalDensity: 0,
    textureTags: ["smooth", "warm", "slow-pulse"],
    regulationTargets: ["downshift", "maintain"],
    familiarityScore: 0.45,
    noveltyWeight: 0.34,
    artistCredibility: 0.5,
  },
  {
    id: "demo-downshift-02",
    title: "Demo: Low Lantern",
    artist: "Hum Demo Catalogue",
    provider: "local",
    genreTags: ["ambient", "piano"],
    bpm: 72,
    energy: 0.28,
    valence: 0.5,
    instrumentalness: 1,
    lyricalDensity: 0,
    textureTags: ["soft", "minimal", "smooth"],
    regulationTargets: ["downshift", "ground"],
    familiarityScore: 0.5,
    noveltyWeight: 0.25,
    artistCredibility: 0.5,
  },
  {
    id: "demo-downshift-03",
    title: "Demo: Slow Harbor",
    artist: "Hum Demo Catalogue",
    provider: "local",
    genreTags: ["downtempo", "ambient"],
    bpm: 78,
    energy: 0.36,
    valence: 0.48,
    instrumentalness: 0.88,
    lyricalDensity: 0.08,
    textureTags: ["rounded", "steady", "low-dynamics"],
    regulationTargets: ["downshift"],
    familiarityScore: 0.42,
    noveltyWeight: 0.4,
    artistCredibility: 0.5,
  },
  {
    id: "demo-ground-01",
    title: "Demo: Walking Grid",
    artist: "Hum Demo Catalogue",
    provider: "local",
    genreTags: ["instrumental", "minimal"],
    bpm: 84,
    energy: 0.42,
    valence: 0.52,
    instrumentalness: 0.96,
    lyricalDensity: 0,
    textureTags: ["steady", "repetitive", "predictable-pulse"],
    regulationTargets: ["ground", "focus"],
    familiarityScore: 0.52,
    noveltyWeight: 0.28,
    artistCredibility: 0.5,
  },
  {
    id: "demo-ground-02",
    title: "Demo: Tabletop Rhythm",
    artist: "Hum Demo Catalogue",
    provider: "local",
    genreTags: ["lo-fi", "instrumental"],
    bpm: 88,
    energy: 0.46,
    valence: 0.55,
    instrumentalness: 0.9,
    lyricalDensity: 0.02,
    textureTags: ["steady", "repetitive", "dry"],
    regulationTargets: ["ground", "maintain"],
    familiarityScore: 0.6,
    noveltyWeight: 0.25,
    artistCredibility: 0.5,
  },
  {
    id: "demo-ground-03",
    title: "Demo: Even Steps",
    artist: "Hum Demo Catalogue",
    provider: "local",
    genreTags: ["acoustic", "instrumental"],
    bpm: 82,
    energy: 0.38,
    valence: 0.58,
    instrumentalness: 0.95,
    lyricalDensity: 0,
    textureTags: ["steady", "simple", "warm"],
    regulationTargets: ["ground"],
    familiarityScore: 0.55,
    noveltyWeight: 0.3,
    artistCredibility: 0.5,
  },
  {
    id: "demo-lift-01",
    title: "Demo: Morning Thread",
    artist: "Hum Demo Catalogue",
    provider: "local",
    genreTags: ["indie-pop", "soft-electronic"],
    bpm: 96,
    energy: 0.58,
    valence: 0.72,
    instrumentalness: 0.55,
    lyricalDensity: 0.22,
    textureTags: ["warm", "bright", "light-groove"],
    regulationTargets: ["gentle_lift", "maintain"],
    familiarityScore: 0.62,
    noveltyWeight: 0.32,
    artistCredibility: 0.5,
  },
  {
    id: "demo-lift-02",
    title: "Demo: Small Sunrise",
    artist: "Hum Demo Catalogue",
    provider: "local",
    genreTags: ["soul", "instrumental"],
    bpm: 102,
    energy: 0.6,
    valence: 0.76,
    instrumentalness: 0.82,
    lyricalDensity: 0.04,
    textureTags: ["warm", "groove", "rounded"],
    regulationTargets: ["gentle_lift"],
    familiarityScore: 0.58,
    noveltyWeight: 0.36,
    artistCredibility: 0.5,
  },
  {
    id: "demo-lift-03",
    title: "Demo: Open Shade",
    artist: "Hum Demo Catalogue",
    provider: "local",
    genreTags: ["folk", "acoustic"],
    bpm: 92,
    energy: 0.52,
    valence: 0.7,
    instrumentalness: 0.72,
    lyricalDensity: 0.12,
    textureTags: ["organic", "warm", "gentle"],
    regulationTargets: ["gentle_lift", "maintain"],
    familiarityScore: 0.57,
    noveltyWeight: 0.3,
    artistCredibility: 0.5,
  },
  {
    id: "demo-focus-01",
    title: "Demo: Clear Desk",
    artist: "Hum Demo Catalogue",
    provider: "local",
    genreTags: ["electronic", "minimal"],
    bpm: 94,
    energy: 0.48,
    valence: 0.54,
    instrumentalness: 0.98,
    lyricalDensity: 0,
    textureTags: ["stable", "clean", "steady"],
    regulationTargets: ["focus", "ground"],
    familiarityScore: 0.5,
    noveltyWeight: 0.4,
    artistCredibility: 0.5,
  },
  {
    id: "demo-focus-02",
    title: "Demo: Soft Circuit",
    artist: "Hum Demo Catalogue",
    provider: "local",
    genreTags: ["electronic", "ambient"],
    bpm: 100,
    energy: 0.54,
    valence: 0.5,
    instrumentalness: 0.94,
    lyricalDensity: 0.01,
    textureTags: ["clean", "looped", "low-volatility"],
    regulationTargets: ["focus"],
    familiarityScore: 0.48,
    noveltyWeight: 0.44,
    artistCredibility: 0.5,
  },
  {
    id: "demo-focus-03",
    title: "Demo: Pencil Lines",
    artist: "Hum Demo Catalogue",
    provider: "local",
    genreTags: ["piano", "instrumental"],
    bpm: 86,
    energy: 0.44,
    valence: 0.55,
    instrumentalness: 1,
    lyricalDensity: 0,
    textureTags: ["minimal", "stable", "soft"],
    regulationTargets: ["focus", "downshift"],
    familiarityScore: 0.54,
    noveltyWeight: 0.24,
    artistCredibility: 0.5,
  },
  {
    id: "demo-release-01",
    title: "Demo: Clean Spark",
    artist: "Hum Demo Catalogue",
    provider: "local",
    genreTags: ["alt-pop", "electronic"],
    bpm: 116,
    energy: 0.72,
    valence: 0.62,
    instrumentalness: 0.46,
    lyricalDensity: 0.28,
    textureTags: ["driving", "bright", "contained"],
    regulationTargets: ["release"],
    familiarityScore: 0.6,
    noveltyWeight: 0.35,
    artistCredibility: 0.5,
    contraindications: ["intensity-sensitive"],
  },
  {
    id: "demo-release-02",
    title: "Demo: Open Road Loop",
    artist: "Hum Demo Catalogue",
    provider: "local",
    genreTags: ["indie-rock", "instrumental"],
    bpm: 124,
    energy: 0.76,
    valence: 0.58,
    instrumentalness: 0.78,
    lyricalDensity: 0.06,
    textureTags: ["driving", "wide", "steady"],
    regulationTargets: ["release"],
    familiarityScore: 0.55,
    noveltyWeight: 0.42,
    artistCredibility: 0.5,
    contraindications: ["intensity-sensitive"],
  },
  {
    id: "demo-release-03",
    title: "Demo: Bright Pressure Valve",
    artist: "Hum Demo Catalogue",
    provider: "local",
    genreTags: ["dance", "electronic"],
    bpm: 118,
    energy: 0.7,
    valence: 0.66,
    instrumentalness: 0.8,
    lyricalDensity: 0.03,
    textureTags: ["pulse", "driving", "clean"],
    regulationTargets: ["release", "gentle_lift"],
    familiarityScore: 0.52,
    noveltyWeight: 0.48,
    artistCredibility: 0.5,
    contraindications: ["intensity-sensitive"],
  },
  {
    id: "demo-maintain-01",
    title: "Demo: Familiar Room",
    artist: "Hum Demo Catalogue",
    provider: "local",
    genreTags: ["lo-fi", "instrumental"],
    bpm: 90,
    energy: 0.5,
    valence: 0.62,
    instrumentalness: 0.88,
    lyricalDensity: 0.04,
    textureTags: ["warm", "steady", "familiar"],
    regulationTargets: ["maintain", "focus"],
    familiarityScore: 0.68,
    noveltyWeight: 0.22,
    artistCredibility: 0.5,
  },
  {
    id: "demo-maintain-02",
    title: "Demo: Balanced Air",
    artist: "Hum Demo Catalogue",
    provider: "local",
    genreTags: ["ambient-pop", "instrumental"],
    bpm: 98,
    energy: 0.52,
    valence: 0.6,
    instrumentalness: 0.8,
    lyricalDensity: 0.08,
    textureTags: ["smooth", "moderate", "stable"],
    regulationTargets: ["maintain"],
    familiarityScore: 0.58,
    noveltyWeight: 0.34,
    artistCredibility: 0.5,
  },
  {
    id: "demo-maintain-03",
    title: "Demo: Quiet Color",
    artist: "Hum Demo Catalogue",
    provider: "local",
    genreTags: ["jazz", "instrumental"],
    bpm: 92,
    energy: 0.5,
    valence: 0.57,
    instrumentalness: 0.94,
    lyricalDensity: 0,
    textureTags: ["organic", "moderate", "clear"],
    regulationTargets: ["maintain", "focus"],
    familiarityScore: 0.5,
    noveltyWeight: 0.45,
    artistCredibility: 0.5,
  },
  {
    id: "demo-ground-04",
    title: "Demo: Repeating Stone",
    artist: "Hum Demo Catalogue",
    provider: "local",
    genreTags: ["percussion", "instrumental"],
    bpm: 76,
    energy: 0.34,
    valence: 0.46,
    instrumentalness: 0.98,
    lyricalDensity: 0,
    textureTags: ["repetitive", "predictable-pulse", "low-dynamics"],
    regulationTargets: ["ground", "downshift"],
    familiarityScore: 0.43,
    noveltyWeight: 0.38,
    artistCredibility: 0.5,
  },
  {
    id: "demo-focus-04",
    title: "Demo: Long Page",
    artist: "Hum Demo Catalogue",
    provider: "local",
    genreTags: ["neo-classical", "instrumental"],
    bpm: 80,
    energy: 0.4,
    valence: 0.53,
    instrumentalness: 1,
    lyricalDensity: 0,
    textureTags: ["minimal", "clear", "low-volatility"],
    regulationTargets: ["focus", "ground"],
    familiarityScore: 0.49,
    noveltyWeight: 0.33,
    artistCredibility: 0.5,
  },
  {
    id: "demo-lift-04",
    title: "Demo: Kind Momentum",
    artist: "Hum Demo Catalogue",
    provider: "local",
    genreTags: ["pop", "instrumental"],
    bpm: 108,
    energy: 0.64,
    valence: 0.74,
    instrumentalness: 0.72,
    lyricalDensity: 0.1,
    textureTags: ["bright", "warm", "groove"],
    regulationTargets: ["gentle_lift", "release"],
    familiarityScore: 0.64,
    noveltyWeight: 0.28,
    artistCredibility: 0.5,
  },
  {
    id: "demo-downshift-04",
    title: "Demo: Dimmer Switch",
    artist: "Hum Demo Catalogue",
    provider: "local",
    genreTags: ["ambient", "drone"],
    bpm: 62,
    energy: 0.2,
    valence: 0.44,
    instrumentalness: 1,
    lyricalDensity: 0,
    textureTags: ["smooth", "minimal", "low-dynamics"],
    regulationTargets: ["downshift"],
    familiarityScore: 0.38,
    noveltyWeight: 0.42,
    artistCredibility: 0.5,
  },
  {
    id: "demo-maintain-04",
    title: "Demo: Middle Current",
    artist: "Hum Demo Catalogue",
    provider: "local",
    genreTags: ["soft-electronic", "instrumental"],
    bpm: 100,
    energy: 0.56,
    valence: 0.58,
    instrumentalness: 0.86,
    lyricalDensity: 0.03,
    textureTags: ["moderate", "smooth", "clean"],
    regulationTargets: ["maintain", "gentle_lift"],
    familiarityScore: 0.56,
    noveltyWeight: 0.36,
    artistCredibility: 0.5,
  },
];

export function getDemoTracksById(trackIds: string[]) {
  const tracksById = new Map(demoMusicCatalog.map((track) => [track.id, track]));
  return trackIds.map((trackId) => tracksById.get(trackId)).filter((track): track is MusicTrack => Boolean(track));
}
